// Solar system planets and dwarf planets data
// Includes orbital parameters, physical characteristics, and moons

export const planetsData = [
  {
    name: "Mercury",
    distance: 39,
    period: 88,
    size: 0.38 * 5,
    color: "#8C7853",
    angle: 0,
    orbitalInclination: 7.0,
    moons: [],
  },
  {
    name: "Venus",
    distance: 72,
    period: 225,
    size: 0.95 * 5,
    color: "#FFC649",
    angle: Math.PI / 3,
    orbitalInclination: 3.39,
    moons: [],
  },
  {
    name: "Earth",
    distance: 100,
    period: 365,
    size: 5,
    color: "#4A90E2",
    angle: Math.PI / 2,
    orbitalInclination: 0.0,
    moons: [
      {
        name: "Moon",
        distance: 15,
        period: 27.3,
        size: 0.27 * 5,
        color: "#C0C0C0",
        angle: 0,
        orbitalInclination: 5.14,
      },
    ],
  },
  {
    name: "Mars",
    distance: 152,
    period: 687,
    size: 0.53 * 5,
    color: "#E27B58",
    angle: Math.PI,
    orbitalInclination: 1.85,
    moons: [
      {
        name: "Phobos",
        distance: 8,
        period: 0.32,
        size: 0.5,
        color: "#8C7853",
        angle: 0,
        orbitalInclination: 1.08,
      },
      {
        name: "Deimos",
        distance: 12,
        period: 1.26,
        size: 0.4,
        color: "#9C8863",
        angle: Math.PI,
        orbitalInclination: 0.93,
      },
    ],
  },
  {
    name: "Jupiter",
    distance: 520,
    period: 4333,
    size: 11.21 * 5,
    color: "#C88B3A",
    angle: Math.PI * 1.5,
    orbitalInclination: 1.31,
    moons: [
      {
        name: "Io",
        distance: 25,
        period: 1.77,
        size: 0.29 * 5,
        color: "#FFD700",
        angle: 0,
        orbitalInclination: 0.05,
      },
      {
        name: "Europa",
        distance: 35,
        period: 3.55,
        size: 0.25 * 5,
        color: "#F5E6D3",
        angle: Math.PI / 2,
        orbitalInclination: 0.47,
      },
      {
        name: "Ganymede",
        distance: 50,
        period: 7.15,
        size: 0.41 * 5,
        color: "#B8A890",
        angle: Math.PI,
        orbitalInclination: 0.2,
      },
      {
        name: "Callisto",
        distance: 70,
        period: 16.69,
        size: 0.38 * 5,
        color: "#8B7355",
        angle: Math.PI * 1.5,
        orbitalInclination: 0.51,
      },
      {
        name: "Himalia",
        distance: 300,
        period: 250,
        size: 0.04 * 5,
        color: "#A2977E",
        angle: Math.PI / 4,
        orbitalInclination: 27.5,
      },
    ],
  },
  {
    name: "Saturn",
    distance: 954,
    period: 10759,
    size: 9.45 * 5,
    color: "#FAD5A5",
    angle: Math.PI * 0.7,
    orbitalInclination: 2.49,
    moons: [
      {
        name: "Titan",
        distance: 60,
        period: 15.95,
        size: 0.4 * 5,
        color: "#FFA500",
        angle: 0,
        orbitalInclination: 0.35,
      },
      {
        name: "Rhea",
        distance: 40,
        period: 4.52,
        size: 0.12 * 5,
        color: "#E8E8E8",
        angle: Math.PI / 3,
        orbitalInclination: 0.35,
      },
      {
        name: "Iapetus",
        distance: 80,
        period: 79.33,
        size: 0.11 * 5,
        color: "#A0A0A0",
        angle: Math.PI,
        orbitalInclination: 15.47,
      },
      {
        name: "Enceladus",
        distance: 25,
        period: 1.37,
        size: 0.04 * 5,
        color: "#DDEFFF",
        angle: Math.PI / 2,
        orbitalInclination: 0.02,
      },
      {
        name: "Mimas",
        distance: 20,
        period: 0.94,
        size: 0.035 * 5,
        color: "#C7C7C7",
        angle: Math.PI / 1.2,
        orbitalInclination: 1.53,
      },
    ],
  },
  {
    name: "Uranus",
    distance: 1920,
    period: 30687,
    size: 4.01 * 5,
    color: "#4FD0E0",
    angle: Math.PI * 1.8,
    orbitalInclination: 0.77,
    moons: [
      {
        name: "Titania",
        distance: 35,
        period: 8.71,
        size: 0.12 * 5,
        color: "#C8D8E8",
        angle: 0,
        orbitalInclination: 0.14,
      },
      {
        name: "Oberon",
        distance: 45,
        period: 13.46,
        size: 0.12 * 5,
        color: "#B8C8D8",
        angle: Math.PI,
        orbitalInclination: 0.1,
      },
      {
        name: "Ariel",
        distance: 30,
        period: 2.52,
        size: 0.09 * 5,
        color: "#C3E0E8",
        angle: Math.PI / 2,
        orbitalInclination: 0.26,
      },
      {
        name: "Umbriel",
        distance: 35,
        period: 4.14,
        size: 0.08 * 5,
        color: "#A9BAC8",
        angle: Math.PI / 1.2,
        orbitalInclination: 0.13,
      },
      {
        name: "Miranda",
        distance: 20,
        period: 1.41,
        size: 0.04 * 5,
        color: "#E9EFFF",
        angle: Math.PI * 1.5,
        orbitalInclination: 4.22,
      },
    ],
  },
  {
    name: "Neptune",
    distance: 3006,
    period: 60190,
    size: 3.88 * 5,
    color: "#4166F5",
    angle: Math.PI * 0.3,
    orbitalInclination: 1.77,
    moons: [
      {
        name: "Triton",
        distance: 30,
        period: 5.88,
        size: 0.21 * 5,
        color: "#D8E8F8",
        angle: 0,
        orbitalInclination: 156.83,
      },
      {
        name: "Proteus",
        distance: 20,
        period: 1.12,
        size: 0.05 * 5,
        color: "#9FAFBF",
        angle: Math.PI / 2,
        orbitalInclination: 0.02,
      },
    ],
  },
  // Dwarf planets and large asteroid belt objects
  {
    name: "Ceres",
    distance: 280, // approx 2.8 AU x 100 for scale
    period: 1682, // 4.6 years in days
    size: 0.0747 * 5, // diameter about 939 km, ratio relative to Earth
    color: "#A9A9A9", // grayish
    angle: Math.PI / 4,
    orbitalInclination: 10.6,
    moons: [],
  },
  {
    name: "Pluto",
    distance: 3940, // 39.4 AU x 100 approx
    period: 90560, // 248 years in days
    size: 0.186 * 5, // diameter approx 2376 km, relative to Earth
    color: "#D2B48C",
    angle: Math.PI / 6,
    orbitalInclination: 17.2,
    moons: [
      {
        name: "Charon",
        distance: 19,
        period: 6.38,
        size: 0.08 * 5,
        color: "#B0B0B0",
        angle: 0,
        orbitalInclination: 0,
      },
      {
        name: "Styx",
        distance: 25,
        period: 20.2,
        size: 0.01 * 5,
        color: "#999999",
        angle: Math.PI / 3,
        orbitalInclination: 0,
      },
      {
        name: "Nix",
        distance: 30,
        period: 24.9,
        size: 0.015 * 5,
        color: "#CCCCCC",
        angle: Math.PI / 2,
        orbitalInclination: 0,
      },
      {
        name: "Kerberos",
        distance: 35,
        period: 32.1,
        size: 0.008 * 5,
        color: "#AAAAAA",
        angle: Math.PI,
        orbitalInclination: 0,
      },
      {
        name: "Hydra",
        distance: 40,
        period: 38.2,
        size: 0.02 * 5,
        color: "#BBBBBB",
        angle: Math.PI * 1.5,
        orbitalInclination: 0,
      },
    ],
  },
  {
    name: "Haumea",
    distance: 4300, // approx 43 AU x 100
    period: 103000, // approx 283 years in days
    size: 0.06 * 5, // diameter approx 1316 km
    color: "#D9F0FF",
    angle: Math.PI / 5,
    orbitalInclination: 28.2,
    moons: [],
  },
  {
    name: "Eris",
    distance: 6800, // approx 68 AU x 100
    period: 204000, // approx 560 years in days
    size: 0.08 * 5, // diameter approx 2326 km
    color: "#E6E6FA",
    angle: Math.PI / 7,
    orbitalInclination: 44,
    moons: [
      {
        name: "Dysnomia",
        distance: 37,
        period: 16,
        size: 0.01 * 5,
        color: "#AAAAAA",
        angle: 0,
        orbitalInclination: 0,
      },
    ],
  },
];
